version: '3'

services:
  timescale-primary:
    image: timescale-replication:latest
    env_file:
        - primary.env
#    environment:
#        REPLICATION_SUBNET: '10.0.0.0/24'
    ports:
        - 5432:5432

  timescale-replica:
    image: timescale-replication:latest
    env_file:
        - replica.env
    ports:
        - 5433:5432
